import { Globe2 } from "lucide-react";
import React from "react";

type Props = {};

const NotFound = (props: Props) => {
  return (
    <div className="flex flex-col min-h-[78vh] w-full justify-center items-center gap-5">
      <Globe2 />
      <div className="flex flex-col items-center justify-center text-center gap-5">
        <p className="text-3xl font-semibold text-primary">
          Nothing to see here
        </p>
        <p className="text-base font-normal">
          So here is a random image generated by{" "}
          <span className="text-slidea">Creative AI</span>
        </p>
      </div>
    </div>
  );
};
export default NotFound;
